# -*- coding: utf-8 -*-
# as of 08-29-2017
PARAMS = {'learning_rate': 0.1,
          'n_estimators': 100,
          'max_depth': 5,
          'min_child_weight': 1,
          'gamma': 0.3,
          'reg_alpha': 0.005,
          'subsample': 0.8,
          'colsample_bytree': 0.8,
          'objective': 'binary:logistic',
          'nthread': 4,
          'seed': 27,
          'scale_pos_weight': 1}

TRAIN_PATH = '/Users/huzuoliang/source/my_ml4/CTR_P/out/artifacts/ctr_p_jar/data/train/1007.csv'
TEST_PATH = '/Users/huzuoliang/source/my_ml4/CTR_P/out/artifacts/ctr_p_jar/data/train/1008.csv'
TRAIN_OUT = 'train_modified_test.csv'
TEST_OUT = 'test_modified_test.csv'

COL_NAMES=['pro_id',
           'guid',
           'broker_id',
           'city_id',
           'url_oh',
           'url_kw_oh',
           'click_clock',
           'agent_oh',
           'label',
           'rent_type_oh',
           'region_id_num',
           'subregion_id_num',
           'comm_id',
           'room_num',
           'hall_num',
           'toilet_num',
           'pro_area',
           'pro_price',
           'paymoney_num_oh',
           'pro_floor',
           'floor_num',
           'decorate_oh',
           'toward_oh',
           'deploy_oh',
           'in_flag',
           'status_oh',
           'pro_type',
           'created_days',
           'updated_days',
           'many_pictures',
           'price_desc_oh',
           'favorites_cnt',
           'today_pro_clicks',
           'pro_history_clicks',
           'is_jx',
           'is_first',
           'is_balcony',
           'is_elevator',
           'is_new',
           'is_park',
           'is_lbrz',
           'is_jdqq',
           'is_mfzj',
           'is_ssrz',
           'is_cgh',
           'is_qxzx',
           'is_qzqp',
           'is_dlwsj',
           'is_zw',
           'is_dlws',
           'is_school',
           'is_subway',
           'score',
           'is_queue_j_2am',
           'is_pm_j_2am',
           'avg_offer_pm_j_2am',
           'is_pm',
           'is_pm_d',
           'online_time_d',
           'is_pm_j',
           'is_window_ad_pm',
           'is_not_spread',
           'cmpy',
           'company_id',
           'store_id',
           'team_id',
           'mobile',
           'tsr_worker_num',
           'broker_lifecycle_oh',
           'reg_time_days',
           'broker_sex_oh',
           'broker_age',
           'main_business_oh',
           'recharge_amount_sum',
           'company_recharge_amount_sum',
           'person_recharge_times_sum',
           'company_recharge_times_sum',
           'pm_prop_zf_sum',
           'not_pm_prop_zf_sum',
           'pm_prop_zf_d_sum',
           'pm_prop_zf_d_hq_sum',
           'pm_prop_zf_j_sum',
           'pm_prop_zf_j_hq_sum',
           'new_prop_zf_sum',
           'new_pm_prop_zf_sum',
           'arrearage_window_ad_zf_sum',
           'impression_window_ad_zf_sum',
           'pm_prop_window_ad_zf_sum',
           'vppv_valid_zf_sum',
           'vppv_valid_zf_d_sum',
           'vppv_valid_zf_d_touch_sum',
           'vppv_valid_zf_j_sum',
           'vppv_valid_zf_j_touch_sum',
           'vppv_valid_zf_pay_sum',
           'vppv_valid_zf_pay_d_sum',
           'vppv_valid_zf_pay_j_sum',
           'consume_amount_zf_sum',
           'consume_amount_d_zf_sum',
           'consume_amount_j_zf_sum',
           'refund_amount_zf_sum',
           'refund_amount_d_zf_sum',
           'refund_amount_j_zf_sum',
           'revenue_accounting_zf_haopan_sum',
           'revenue_accounting_zf_selection_pm_sum',
           'revenue_accounting_zf_window_ad_sum',
           'revenue_accounting_zf_order_sum',
           'revenue_accounting_zf_combo_sum',
           'upload_videos_sum',
           'pass_videos_sum',
           'nopass_videos_sum',
           'video_prop_pm_sum',
           'video_prop_pm_j_sum',
           'video_vppv_valid_sum',
           'video_vppv_valid_j_sum',
           'user_history_clicks',
           'price_desc_like_oh',
           'area_id_like',
           'room_num_like',
           'decorate_like_oh',
           'hall_num_like',
           'rent_type_like_oh',
           'today_user_clicks'] # bigint

COL_DROP = ['city_id', 'in_flag',
            'comm_id', 'score',
            'broker_id','cmpy',
            'company_id', 'store_id',
            'team_id', 'mobile',
            'today_user_clicks', 'today_pro_clicks',
            'subregion_id_num', 'region_id_num',
            'price_desc','price_desc_like']

COL_ENCODE = ['searchType','hasSearchKey','user_device','rent_type','paymoney_num',
              'most_decorate','toward','status','broker_lifecycle','broker_sex',
              'main_business','decorate_like','rent_type_like']

RE_INEX_NAME = ['click_clock',
                'label',
                'room_num',
                'hall_num',
                'toilet_num',
                'pro_area',
                'pro_price',
                'pro_floor',
                'floor_num',
                'in_flag',
                'pro_type',
                'created_days',
                'updated_days',
                'many_pictures',
                'favorites_cnt',
                'pro_history_clicks',
                'is_jx',
                'is_first',
                'is_balcony',
                'is_elevator',
                'is_new',
                'is_park',
                'is_lbrz',
                'is_jdqq',
                'is_mfzj',
                'is_ssrz',
                'is_cgh',
                'is_qxzx',
                'is_qzqp',
                'is_dlwsj',
                'is_zw',
                'is_dlws',
                'is_school',
                'is_subway',
                'score',
                'is_queue_j_2am',
                'is_pm_j_2am',
                'avg_offer_pm_j_2am',
                'is_pm',
                'is_pm_d',
                'online_time_d',
                'is_pm_j',
                'is_window_ad_pm',
                'is_not_spread',
                'cmpy',
                'tsr_worker_num',
                'reg_time_days',
                'broker_age',
                'recharge_amount_sum',
                'company_recharge_amount_sum',
                'person_recharge_times_sum',
                'company_recharge_times_sum',
                'pm_prop_zf_sum',
                'not_pm_prop_zf_sum',
                'pm_prop_zf_d_sum',
                'pm_prop_zf_d_hq_sum',
                'pm_prop_zf_j_sum',
                'pm_prop_zf_j_hq_sum',
                'new_prop_zf_sum',
                'new_pm_prop_zf_sum',
                'arrearage_window_ad_zf_sum',
                'impression_window_ad_zf_sum',
                'pm_prop_window_ad_zf_sum',
                'vppv_valid_zf_sum',
                'vppv_valid_zf_d_sum',
                'vppv_valid_zf_d_touch_sum',
                'vppv_valid_zf_j_sum',
                'vppv_valid_zf_j_touch_sum',
                'vppv_valid_zf_pay_sum',
                'vppv_valid_zf_pay_d_sum',
                'vppv_valid_zf_pay_j_sum',
                'consume_amount_zf_sum',
                'consume_amount_d_zf_sum',
                'consume_amount_j_zf_sum',
                'refund_amount_zf_sum',
                'refund_amount_d_zf_sum',
                'refund_amount_j_zf_sum',
                'revenue_accounting_zf_haopan_sum',
                'revenue_accounting_zf_selection_pm_sum',
                'revenue_accounting_zf_window_ad_sum',
                'revenue_accounting_zf_order_sum',
                'revenue_accounting_zf_combo_sum',
                'upload_videos_sum',
                'pass_videos_sum',
                'nopass_videos_sum',
                'video_prop_pm_sum',
                'video_prop_pm_j_sum',
                'video_vppv_valid_sum',
                'video_vppv_valid_j_sum',
                'user_history_clicks',
                'room_num_like',
                'hall_num_like']

COL_ENCODE_VOCABULARY = {#'url_oh' : list(range(-1, 4)),
                         #'url_kw_oh' : list(range(-1, 2)),
                         #'agent_oh' : list(range(-1, 9)),
                         'rent_type_oh' : list(range(-1, 2)),
                         'paymoney_num_oh' : list(range(-1, 13)),
                         'decorate_oh' : list(range(-1, 7)),
                         'toward_oh' : list(range(-1, 10)),
                         'status_oh' : list(range(-1, 2)),
                         'price_desc_oh' : list(range(-1, 9)),
                         'broker_lifecycle_oh' : list(range(-1, 10)),
                         'broker_sex_oh' : list(range(-1, 2)),
                         'main_business_oh' : list(range(-1, 2)),
                         'price_desc_like_oh' : list(range(-1, 9)),
                         'area_id_like' : list(range(-1, 11)),
                         'decorate_like_oh' : list(range(-1, 7)),
                         'rent_type_like_oh' : list(range(-1, 2))}
